import Head from 'next/head'
import { Rubik } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { QR, Bar } from '@/components/Generator'
import { Tabs, TabLink } from '@/components/Tabs'
import { useTabs } from '@/hooks'

const rubik = Rubik({ subsets: ['latin'] })

export default function Home() {

  const tabs = useTabs({
    tabs: [
      {
        child: <Bar />,
        label: "Bar Code",
        target: "bar"
      },
      {
        child: <QR />,
        label: "QR Code",
        target: "qr"
      }
    ],
    initial: "bar"
  });

  return (
    <>
      <Head>
        <title>NextJS QR-Bar Generator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${rubik.className}`}>
        <div style={{ position: "fixed", top: "1.5rem", left: "1.5rem" }}>
          <Tabs {...tabs.props} />
        </div>
        {tabs.pane}
        {/* <Bar /> */}
        {/* <QR /> */}
      </main>
    </>
  )
}
